version: '3.8'

services:
    bct-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9117:9117"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: bct
            DB_USERNAME: bct_user
            DB_PASSWORD: password
    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: bct
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: bct_user
            MYSQL_PASSWORD: password
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    mysql-data:
